/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-04-22 04:33:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002dmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/include-head.jsp", Long.valueOf(1586946003000L));
    _jspx_dependants.put("/WEB-INF/include-sidebar.jsp", Long.valueOf(1587527500000L));
    _jspx_dependants.put("/WEB-INF/include-navigator.jsp", Long.valueOf(1587023898000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"UTF-8\">\n");
      out.write("<!-- 提取出navigator部分，单独包含进来 -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"GB18030\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<base\n");
      out.write("\thref=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\n");
      out.write("<style>\n");
      out.write(".tree li {\n");
      out.write("\tlist-style-type: none;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tree-closed {\n");
      out.write("\theight: 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tree-expanded {\n");
      out.write("\theight: auto;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script src=\"jquery/jquery-2.1.1.min.js\"></script>\n");
      out.write("<script src=\"bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"script/docs.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"layer/layer.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\t\t$(\".list-group-item\").click(function() {\n");
      out.write("\t\t\tif ($(this).find(\"ul\")) {\n");
      out.write("\t\t\t\t$(this).toggleClass(\"tree-closed\");\n");
      out.write("\t\t\t\tif ($(this).hasClass(\"tree-closed\")) {\n");
      out.write("\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t$(\"ul\", this).show(\"fast\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- 提取出navigator部分，单独包含进来 -->\n");
      out.write("\t");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" style=\"font-size: 32px;\" href=\"#\">众筹平台\n");
      out.write("\t\t\t\t\t\t- 控制面板</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t<li style=\"padding-top: 8px;\">\n");
      out.write("\t\t\t\t\t\t<div class=\"btn-group\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-default btn-success dropdown-toggle\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginAdmin.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" \n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"caret\"></span>\n");
      out.write("\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t个人设置</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t消息</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"divider\"></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"admin/do/logout.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li style=\"margin-left: 10px; padding-top: 8px;\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-right\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"查询\">\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 提取出sidebar部分，单独包含进来 -->\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("<div class=\"col-sm-3 col-md-2 sidebar\">\n");
      out.write("\t\t\t\t<div class=\"tree\">\n");
      out.write("\t\t\t\t\t<ul style=\"padding-left: 0px;\" class=\"list-group\">\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"main.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item tree-closed\"><span><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"badge\" style=\"float: right\">3</span></span>\n");
      out.write("\t\t\t\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"admin/get/page.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></i> 用户维护</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"role/to/page.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-king\"></i> 角色维护</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"menu/to/page.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></i> 菜单维护</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item tree-closed\"><span><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"float: right\">3</span></span>\n");
      out.write("\t\t\t\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_cert.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 实名认证审核</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_adv.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 广告审核</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"auth_project.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-check\"></i> 项目审核</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item tree-closed\"><span><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"badge\" style=\"float: right\">7</span></span>\n");
      out.write("\t\t\t\t\t\t\t<ul style=\"margin-top: 10px; display: none;\">\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"cert.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-picture\"></i> 资质维护</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"type.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"process.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-random\"></i> 流程管理</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"advertisement.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-hdd\"></i> 广告管理</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"message.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-comment\"></i> 消息模板</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"project_type.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list\"></i> 项目分类</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li style=\"height: 30px;\"><a href=\"tag.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-tags\"></i> 项目标签</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"list-group-item tree-closed\"><a href=\"param.html\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- 页面主体内容 -->\n");
      out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\n");
      out.write("\t\t\t\t<h1 class=\"page-header\">控制面板</h1>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row placeholders\">\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-3 placeholder\">\n");
      out.write("\t\t\t\t\t\t<img data-src=\"holder.js/200x200/auto/sky\" class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\talt=\"Generic placeholder thumbnail\">\n");
      out.write("\t\t\t\t\t\t<h4>Label</h4>\n");
      out.write("\t\t\t\t\t\t<span class=\"text-muted\">Something else</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-3 placeholder\">\n");
      out.write("\t\t\t\t\t\t<img data-src=\"holder.js/200x200/auto/vine\" class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\talt=\"Generic placeholder thumbnail\">\n");
      out.write("\t\t\t\t\t\t<h4>Label</h4>\n");
      out.write("\t\t\t\t\t\t<span class=\"text-muted\">Something else</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-3 placeholder\">\n");
      out.write("\t\t\t\t\t\t<img data-src=\"holder.js/200x200/auto/sky\" class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\talt=\"Generic placeholder thumbnail\">\n");
      out.write("\t\t\t\t\t\t<h4>Label</h4>\n");
      out.write("\t\t\t\t\t\t<span class=\"text-muted\">Something else</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-6 col-sm-3 placeholder\">\n");
      out.write("\t\t\t\t\t\t<img data-src=\"holder.js/200x200/auto/vine\" class=\"img-responsive\"\n");
      out.write("\t\t\t\t\t\t\talt=\"Generic placeholder thumbnail\">\n");
      out.write("\t\t\t\t\t\t<h4>Label</h4>\n");
      out.write("\t\t\t\t\t\t<span class=\"text-muted\">Something else</span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
