/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-04-28 13:20:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	pageContext.setAttribute("PATH", request.getContextPath());

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>登入 - layuiAdmin</title>\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/layui/css/layui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/layui/css/admin.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/layui/css/all.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"layadmin-user-login layadmin-user-display-show\"\r\n");
      out.write("\t\t\tid=\"LAY-user-login\" style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SPRING_SECURITY_LAST_EXCEPTION.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/do/login.html\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"layadmin-user-login-main\">\r\n");
      out.write("\t\t\t\t<div class=\"layadmin-user-login-box layadmin-user-login-header\">\r\n");
      out.write("\t\t\t\t\t<h2>layuiAdmin</h2>\r\n");
      out.write("\t\t\t\t\t<p>layui 官方出品的单页面后台管理模板系统</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"layadmin-user-login-box layadmin-user-login-body layui-form\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layadmin-user-login-icon layui-icon layui-icon-username\"\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"LAY-user-login-username\"></label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- input的name属性值必须符合SpringSecurity规则，除非专门进行了定制，否则用户名必须使用username，密码必须使用password -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"loginAcct\" id=\"LAY-user-login-username\"\r\n");
      out.write("\t\t\t\t\t\t\tlay-verify=\"required\" placeholder=\"用户名\" class=\"layui-input\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t\t\t\t<label\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layadmin-user-login-icon layui-icon layui-icon-password\"\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"LAY-user-login-password\"></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"userPswd\" id=\"LAY-user-login-password\"\r\n");
      out.write("\t\t\t\t\t\t\tlay-verify=\"required\" placeholder=\"密码\" class=\"layui-input\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"layui-row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"layui-col-xs7\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"layadmin-user-login-icon layui-icon layui-icon-vercode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"LAY-user-login-vercode\"></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"vercode\" id=\"LAY-user-login-vercode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlay-verify=\"required\" placeholder=\"图形验证码\" class=\"layui-input\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"layui-col-xs5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"margin-left: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"https://www.oschina.net/action/user/captcha\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"layadmin-user-login-codeimg\" id=\"LAY-user-get-vercode\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-form-item\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"remember-me\" lay-skin=\"primary\" title=\"记住我\"> \r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"forget.html\" class=\"layadmin-user-jump-change layadmin-link\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-top: 7px;\">忘记密码？</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"layui-btn layui-btn-fluid\" lay-submit\r\n");
      out.write("\t\t\t\t\t\t\tlay-filter=\"LAY-user-login-submit\">登 入</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-trans layui-form-item layadmin-user-login-other\">\r\n");
      out.write("\t\t\t\t\t\t<label>社交账号登入</label> <a href=\"javascript:;\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layui-icon layui-icon-login-qq\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:;\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layui-icon layui-icon-login-wechat\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:;\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layui-icon layui-icon-login-weibo\"></i></a> <a href=\"reg.html\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layadmin-user-jump-change layadmin-link\">注册帐号</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"layui-trans layadmin-user-login-footer\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t© 2018 <a href=\"http://www.layui.com/\" target=\"_blank\">layui.com</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/layui/layui.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tlayui.use([ 'element', 'form' ], function() {\r\n");
      out.write("\t\t\tvar element = layui.element, form = layui.form, layer = layui.layer ;\r\n");
      out.write("\t\t\tform.render();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 假提交\r\n");
      out.write("\t\t\t/* form.on('submit(LAY-user-login-submit)', function(obj) {\r\n");
      out.write("\t\t\t\tobj.elem.classList.add(\"layui-btn-disabled\");//样式上的禁用效果\r\n");
      out.write("\t\t\t\tobj.elem.disabled = true;//真正的禁用效果\r\n");
      out.write("\t\t\t\tlayer.msg(\"登陆成功，即将跳转\");\r\n");
      out.write("\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"main.html\";\r\n");
      out.write("\t\t\t\t}, 2000);\r\n");
      out.write("\t\t\t}); */\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
